image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      npm install
      cd gulp
      yarn
    command: npm run dev
ports:
  - port: 3001
    onOpen: ignore
  - port: 3005
    onOpen: open-preview
vscode:
  extensions:
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
